import type { AiCatalogItem } from "@/types";

export const aiCatalog: AiCatalogItem[] = [
  {
    id: "openai",
    name: "OpenAI GPT",
    category: "redaction",
    strengths: [
      "redaction claire",
      "fiches de révision",
      "scripts",
      "reformulation",
      "pedagogie",
    ],
    status: "active",
  },
  {
    id: "claude",
    name: "Claude",
    category: "redaction",
    strengths: ["analyse longue", "structuration", "textes longs"],
    status: "active",
  },
  {
    id: "mistral",
    name: "Mistral",
    category: "redaction",
    strengths: ["modèle européen", "réponses en français"],
    status: "planned",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "redaction",
    strengths: ["modèle généraliste", "documents longs"],
    status: "active",
  },
  {
    id: "perplexity",
    name: "Perplexity Sonar",
    category: "research",
    strengths: ["recherche web", "sources", "actualite"],
    status: "active",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "research",
    strengths: ["recherche liée à l'écosystème Google"],
    status: "active",
  },
  {
    id: "openai",
    name: "OpenAI avec web search si disponible",
    category: "research",
    strengths: ["recherche generale", "synthese"],
    status: "active",
  },
  {
    id: "claude",
    name: "Claude",
    category: "code",
    strengths: ["architecture", "debugging", "gros fichiers"],
    status: "active",
  },
  {
    id: "openai",
    name: "OpenAI GPT",
    category: "code",
    strengths: ["explication du code", "fonctions propres"],
    status: "active",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "code",
    strengths: ["analyse de code", "multimodal"],
    status: "active",
  },
  {
    id: "codestral",
    name: "Mistral Codestral",
    category: "code",
    strengths: ["spécialisé code"],
    status: "planned",
  },
  {
    id: "claude",
    name: "Claude",
    category: "summary",
    strengths: ["longs documents", "analyse de cours"],
    status: "active",
  },
  {
    id: "openai",
    name: "OpenAI GPT",
    category: "summary",
    strengths: ["transformation en fiche claire"],
    status: "active",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "summary",
    strengths: ["documents longs", "multimodal"],
    status: "active",
  },
  {
    id: "openai",
    name: "OpenAI GPT",
    category: "oral",
    strengths: ["script naturel", "ton humain", "presentation orale"],
    status: "active",
  },
  {
    id: "claude",
    name: "Claude",
    category: "oral",
    strengths: ["structure logique", "plan détaillé"],
    status: "active",
  },
  {
    id: "dalle",
    name: "DALL-E / GPT Image",
    category: "image",
    strengths: ["création d'images"],
    status: "planned",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    category: "image",
    strengths: ["images creatives"],
    status: "planned",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    category: "image",
    strengths: ["images open source"],
    status: "planned",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    category: "image",
    strengths: ["design commercial"],
    status: "planned",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "audio",
    strengths: ["voix realistes"],
    status: "planned",
  },
  {
    id: "openai-audio",
    name: "OpenAI Audio",
    category: "audio",
    strengths: ["transcription", "voix", "audio"],
    status: "planned",
  },
  {
    id: "whisper",
    name: "Whisper",
    category: "audio",
    strengths: ["transcription"],
    status: "planned",
  },
  {
    id: "sora",
    name: "Sora",
    category: "video",
    strengths: ["génération vidéo"],
    status: "planned",
  },
  {
    id: "runway",
    name: "Runway",
    category: "video",
    strengths: ["video creative"],
    status: "planned",
  },
  {
    id: "pika",
    name: "Pika",
    category: "video",
    strengths: ["video courte"],
    status: "planned",
  },
  {
    id: "heygen",
    name: "HeyGen",
    category: "video",
    strengths: ["avatars video"],
    status: "planned",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    category: "video",
    strengths: ["présentation vidéo avec avatar"],
    status: "planned",
  },
];

export const activeAiCatalog = aiCatalog.filter((ai) => ai.status === "active");
